name: main

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir build
          echo 'test-attestation' > build/test-attestation.txt
          date >> build/test-attestation.txt

      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/

      - name: Provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: build/*
